import { useState, useCallback, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, RefreshCw, ArrowRight } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { streamCoachResponse, type ChatMessage } from "@/lib/mentalCoachApi";
import { usePreRoundRecall } from "@/hooks/usePreRoundRecall";
import { useRounds } from "@/hooks/useRounds";
import { loadPatternSummary } from "@/lib/patternInsights";
import { parseStructuredReflectionFromRound } from "@/lib/roundDna";
import { useAuth } from "@/hooks/useAuth";
import { useFeatureFlags } from "@/hooks/useFeatureFlags";
import { savePendingPreGameTalk } from "@/lib/roundSession";
import { getDailyFocus } from "@/lib/dailyFocus";
import { triggerHaptic } from "@/lib/haptics";
import { cn } from "@/lib/utils";

type PreGameStatus = "idle" | "generating" | "ready" | "error";

const GENERIC_PRE_GAME_TALKS = [
  `Nerves are normal. They mean you care. Today, forget the score. Your one job: {{focus:commit}} to every shot. Nothing else matters.`,
  `You do not need a perfect round. You need a {{focus:patient}} start and a clear target on every swing.`,
  `Let the first tee settle you. Breathe once, choose your target, and trust your {{focus:tempo}}.`,
  `Keep the day simple. See it, commit, and let go. Today is about {{focus:trust}} over tension.`,
];

function pickGenericTalk() {
  return GENERIC_PRE_GAME_TALKS[Math.floor(Math.random() * GENERIC_PRE_GAME_TALKS.length)];
}

const PreGame = () => {
  const navigate = useNavigate();
  const { recallLine } = usePreRoundRecall();
  const { features, isLoading: featureLoading } = useFeatureFlags();
  const { getRecentRounds } = useRounds();
  const { user } = useAuth();

  const [talk, setTalk] = useState("");
  const [status, setStatus] = useState<PreGameStatus>("idle");
  const [dailyFocusText, setDailyFocusText] = useState<string | null>(null);

  const hasAutoGenerated = useRef(false);
  const currentRequestId = useRef<string | null>(null);
  const currentAbortController = useRef<AbortController | null>(null);

  const cancelActiveRequest = useCallback(() => {
    currentAbortController.current?.abort();
    currentAbortController.current = null;
  }, []);

  useEffect(() => {
    setDailyFocusText(getDailyFocus()?.text ?? null);
  }, []);

  const buildPersonalizedPrompt = useCallback(async () => {
    const rounds = await getRecentRounds(12);
    const recentStructuredRounds = rounds
      .map((round) => {
        const reflection = parseStructuredReflectionFromRound(round);
        if (!reflection) return null;
        return {
          timestamp: reflection.timestamp,
          emotional_start: reflection.emotional_start,
          emotional_finish: reflection.emotional_finish,
          trigger_type:
            reflection.trigger_type === "Specific hole" && reflection.trigger_hole
              ? `${reflection.trigger_type} (${reflection.trigger_hole})`
              : reflection.trigger_type,
          recovery_quality: reflection.recovery_quality,
          effective_cue: reflection.effective_cue,
        };
      })
      .filter((round): round is NonNullable<typeof round> => Boolean(round))
      .slice(0, 3);

    const patternSummary = loadPatternSummary(user?.id);

    if (recentStructuredRounds.length === 0 && !patternSummary) {
      return null;
    }

    const messages: ChatMessage[] = [
      {
        role: "user",
        content:
          "Create a concise pre-game brief for a golfer. " +
          "Use the last 3 structured rounds and pattern summary. " +
          "Keep it to exactly 3 short lines with this shape:\n" +
          "Last 3 rounds:\n" +
          "<1 sentence on recent tendency>\n" +
          "Focus: <short cue phrase>\n\n" +
          "Be calm, direct, and useful. No intro. No quotes.\n\n" +
          `daily_focus=${JSON.stringify(dailyFocusText)}\n` +
          `last_3_rounds=${JSON.stringify(recentStructuredRounds)}\n` +
          `pattern_summary=${JSON.stringify(patternSummary)}`,
      },
    ];

    return messages;
  }, [dailyFocusText, getRecentRounds, user?.id]);

  const generateTalk = useCallback(async (mode: "auto" | "manual" = "manual") => {
    if (featureLoading) return;
    if (status === "generating") return;
    if (mode === "auto" && hasAutoGenerated.current) return;

    if (mode === "auto") {
      hasAutoGenerated.current = true;
    }

    cancelActiveRequest();

    const requestId = `pregame-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    currentRequestId.current = requestId;
    const abortController = new AbortController();
    currentAbortController.current = abortController;

    setTalk("");
    setStatus("generating");

    if (!features.personalized_brief) {
      if (currentRequestId.current !== requestId) return;
      const fallbackTalk = pickGenericTalk();
      setTalk(fallbackTalk);
      savePendingPreGameTalk(fallbackTalk);
      setStatus("ready");
      currentAbortController.current = null;
      return;
    }

    try {
      const messages = await buildPersonalizedPrompt();
      if (abortController.signal.aborted || currentRequestId.current !== requestId) return;

      if (!messages) {
        const fallbackTalk = pickGenericTalk();
        setTalk(fallbackTalk);
        savePendingPreGameTalk(fallbackTalk);
        setStatus("ready");
        currentAbortController.current = null;
        return;
      }

      let nextContent = "";

      streamCoachResponse({
        messages,
        context: "pre-game",
        signal: abortController.signal,
        onDelta: (delta) => {
          if (currentRequestId.current !== requestId) return;
          nextContent += delta;
          setTalk(nextContent);
        },
        onDone: () => {
          if (currentRequestId.current !== requestId) return;
          const finalTalk = nextContent.trim();
          setTalk(finalTalk);
          savePendingPreGameTalk(finalTalk);
          setStatus("ready");
          currentAbortController.current = null;
        },
        onError: (error) => {
          if (currentRequestId.current !== requestId) return;
          console.error("Failed to load personalized pre-game brief:", error);
          const fallbackTalk = pickGenericTalk();
          setTalk(fallbackTalk);
          savePendingPreGameTalk(fallbackTalk);
          setStatus("error");
          currentAbortController.current = null;
        },
      });
    } catch (error) {
      if (currentRequestId.current !== requestId) return;
      console.error("Failed to prepare pre-game brief:", error);
      const fallbackTalk = pickGenericTalk();
      setTalk(fallbackTalk);
      savePendingPreGameTalk(fallbackTalk);
      setStatus("error");
      currentAbortController.current = null;
    }
  }, [
    buildPersonalizedPrompt,
    cancelActiveRequest,
    featureLoading,
    features.personalized_brief,
    status,
  ]);

  useEffect(() => {
    if (featureLoading || hasAutoGenerated.current) return;
    void generateTalk("auto");
  }, [featureLoading, generateTalk]);

  useEffect(() => {
    return () => {
      cancelActiveRequest();
    };
  }, [cancelActiveRequest]);

  const renderContent = useCallback((text: string) => {
    const parts = text.split(/({{[^}]+}})/g);
    return parts.map((part, index) => {
      const match = part.match(/{{(focus|calm):([^}]+)}}/);
      if (match) {
        const [, type, word] = match;
        const colorClass = type === "focus" ? "text-cue-focus" : "text-cue-calm";
        return (
          <span key={index} className={`font-semibold ${colorClass}`}>
            {word}
          </span>
        );
      }
      return part;
    });
  }, []);

  const handleContinue = () => {
    if (status === "generating") return;
    triggerHaptic("medium");
    navigate("/round-setup");
  };

  const handleAnotherCue = () => {
    if (status === "generating") return;
    triggerHaptic("soft");
    void generateTalk("manual");
  };

  const handleBack = () => {
    triggerHaptic("light");
    navigate("/");
  };

  const isGenerating = status === "generating";

  return (
    <PageShell backgroundVariant="default">
      <div className="flex flex-col h-full">
        {/* Header */}
        <div className="shrink-0 pt-[max(16px,env(safe-area-inset-top))] px-5 pb-2">
          <button
            type="button"
            onClick={handleBack}
            className="inline-flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-medium text-[rgba(26,26,26,0.6)] transition-all duration-200 hover:bg-[rgba(0,0,0,0.03)] active:scale-95"
          >
            <ArrowLeft className="h-4 w-4" />
            Home
          </button>
        </div>

        {/* Main content */}
        <div className="flex-1 flex flex-col items-center justify-center px-6 pb-16">
          <div className="max-w-md w-full space-y-8">
            {/* Title section */}
            <div className="text-center space-y-3">
              <h2 className="text-[32px] font-serif text-[#1a1a1a] tracking-wide leading-tight">
                Pre-Game Talk
              </h2>
              <p className="text-sm text-[rgba(26,26,26,0.6)] tracking-wide">
                Before you step to the first tee.
              </p>

              {dailyFocusText && (
                <p className="text-xs tracking-wide text-[#2d6a4f] pt-1">
                  Today&apos;s focus: {dailyFocusText}
                </p>
              )}

              {recallLine && (
                <p className="text-[11px] text-[rgba(26,26,26,0.6)] opacity-60 font-light italic pt-1">
                  {recallLine}
                </p>
              )}
            </div>

            {/* Coach talk card */}
            <div
              className={cn(
                "rounded-[20px] border border-[rgba(45,106,79,0.12)] p-6 min-h-[160px] backdrop-blur-md transition-all duration-500",
                "bg-[rgba(45,106,79,0.06)]",
                isGenerating && !talk && "flex items-center justify-center"
              )}
            >
              {isGenerating && !talk ? (
                <div className="flex gap-2">
                  <span className="w-2.5 h-2.5 bg-[#2d6a4f] rounded-full opacity-30 animate-pulse" />
                  <span className="w-2.5 h-2.5 bg-[#2d6a4f] rounded-full opacity-30 animate-pulse" style={{ animationDelay: "0.2s" }} />
                  <span className="w-2.5 h-2.5 bg-[#2d6a4f] rounded-full opacity-30 animate-pulse" style={{ animationDelay: "0.4s" }} />
                </div>
              ) : (
                <div className="space-y-3">
                  {talk.split("\n").filter(Boolean).map((line, index) => (
                    <p key={`${line}-${index}`} className="text-[15px] leading-relaxed text-[#1a1a1a]">
                      {renderContent(line)}
                    </p>
                  ))}
                  {status === "error" && (
                    <p className="text-[11px] text-[rgba(26,26,26,0.6)] opacity-50 pt-2">
                      Personalized brief unavailable — showing a stable cue.
                    </p>
                  )}
                </div>
              )}
            </div>

            {/* Action buttons */}
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={handleAnotherCue}
                disabled={isGenerating || featureLoading}
                className="flex-1 inline-flex items-center justify-center gap-2 min-h-[48px] rounded-2xl border border-[rgba(45,106,79,0.12)] bg-[rgba(45,106,79,0.06)] text-sm font-medium text-[#1a1a1a] transition-all duration-200 hover:bg-[rgba(45,106,79,0.06)] active:scale-[0.97] disabled:opacity-40"
              >
                <RefreshCw className={cn("h-4 w-4", isGenerating && "animate-spin")} />
                Another Cue
              </button>

              <button
                type="button"
                onClick={handleContinue}
                disabled={isGenerating}
                className="flex-1 inline-flex items-center justify-center gap-2 min-h-[48px] rounded-2xl bg-[rgba(31,106,74,0.6)] border border-[rgba(31,180,100,0.25)] text-sm font-medium text-[#1a1a1a] shadow-[0_8px_24px_rgba(0,0,0,0.2)] transition-all duration-200 hover:bg-[rgba(31,106,74,0.75)] active:scale-[0.97] disabled:opacity-40"
              >
                Let&apos;s Go
                <ArrowRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </PageShell>
  );
};

export default PreGame;
